version: '2'
services:

  mongodb:
    image: mongo:3
    volumes:
      - graylog_mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.23
    volumes:
      - graylog_es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image: graylog/graylog:4.2.5
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - ../target/graylog-plugin-alertmanagernotify-1.0.0.jar:/usr/share/graylog/plugin/graylog-plugin-alertmanagernotify.jar
    environment:
      - GRAYLOG_PASSWORD_SECRET=RandomPasswordSalt
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
    - 9093:9093

volumes:
  graylog_mongo_data:
    driver: local
  graylog_es_data:
    driver: local
  graylog_journal:
    driver: local
