name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-utils
      - name: Set variables
        run: |
          export GRAYLOG_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="parent"]/*[local-name()="version"]/text()' pom.xml)
          export CACHE_DATE=$(/bin/date -u "+%Y%m%d")
          export GRAYLOG_SERVER_PATH=$(realpath ../graylog2-server)
          echo "GRAYLOG_VERSION=${GRAYLOG_VERSION}" >> $GITHUB_ENV
          echo "CACHE_DATE=${CACHE_DATE}" >> $GITHUB_ENV
          echo "GRAYLOG_SERVER_PATH=${GRAYLOG_SERVER_PATH}" >> $GITHUB_ENV
          echo "Building for Graylog ${GRAYLOG_VERSION} at ${CACHE_DATE}"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.GRAYLOG_SERVER_PATH }}
          key: ${{ runner.os }}-${{ env.CACHE_DATE }}-${{ env.GRAYLOG_VERSION }}
      - name: Initialize Graylog
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Checking out Graylog ${{ env.GRAYLOG_VERSION }}"
          git clone --depth 1 --branch "${{ env.GRAYLOG_VERSION }}" https://github.com/Graylog2/graylog2-server.git ${{ env.GRAYLOG_SERVER_PATH }}
          pushd ${{ env.GRAYLOG_SERVER_PATH }}
          mvn generate-resources -pl graylog2-server -B -V
          popd
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/graylog-plugin*.jar
